/**
 * @file Singelton.hpp
 * @date October 1, 2009
 *
 * Singleton template class can be applied to the
 * application and subsystem classes (selectively).
 */

#ifndef ILL_CORE_SINGLETON_HPP
#define ILL_CORE_SINGLETON_HPP

#include <boost/assert.hpp>

#if ILL_COMPILER == ILL_COMPILER_MSVC
// Turn off warnings generated by this singleton implementation
#pragma  warning ( push )
#   pragma warning ( disable : 4311 )
#   pragma warning ( disable : 4312 )
#endif

namespace Ill
{
	namespace Core
	{
		template< typename T >
		class Singleton 
		{
		public:
			Singleton()
			{
				BOOST_ASSERT( ms_Singleton == NULL );
#if defined( _MSC_VER ) && _MSC_VER < 1200	 
                // Calculate the offset from the starting address of type T
                // and the address of type Singelton<T> so that we can get
                // the address of type T and not Singelton<T> from the "this" pointer.
                // For a better explanation of this Singelton implementation, refer to 
                // Chapter 1.3 "An Automatic Singleton Utility" by Scott Bilas in
                // Game Programming Gems (2000), Charles River Media, Inc.
				int offset = (int)(T*)1 - (int)(Singleton <T>*)(T*)1;
				ms_Singleton = (T*)((int)this + offset);
#else
				ms_Singleton = static_cast< T* >( this );
#endif
			}

			virtual ~Singleton( void )
			{  
				BOOST_ASSERT( ms_Singleton != NULL );  
				ms_Singleton = NULL;  
			}

			static T& Get()
			{	
				BOOST_ASSERT( ms_Singleton != NULL );  
				return ( *ms_Singleton ); 
			}

			static T* GetPtr()
			{ 
				return ms_Singleton; 
			}


		protected:
			static T* ms_Singleton;

        private:
            /** 
             * Explicit private copy constructor. This is a forbidden operation.
             */
            Singleton(const Singleton<T> &);

            /** 
             * Private operator= . This is a forbidden operation. 
             */
            Singleton& operator=(const Singleton<T> &);

		};
	}
}

#if ILL_COMPILER == ILL_COMPILER_MSVC
// Turn off warnings generated by this singleton implementation
#pragma  warning ( pop )
#endif

#endif // ILL_CORE_SINGLETON_HPP