#ifndef ILL_SYSTEM_OGREGRAPHICS_PRECOMPILED_HEADER_HPP
#define ILL_SYSTEM_OGREGRAPHICS_PRECOMPILED_HEADER_HPP

#include <Ill/System/System.hpp>

#endif // ILL_SYSTEM_OGREGRAPHICS_PRECOMPILED_HEADER_HPP
